# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
env:
  ACT_NODE_VERSION: 12.x
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: [self-hosted, vmslave]
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          submodules: 'recursive'
      - name: Bump version and push tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          tag_prefix: ~
          default_bump: minor
          release_branches: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: print tag
        run: echo ${{ steps.create_tag.outputs.new_tag }}
      - name: get commit message
        run: |
          echo ::set-env name=COMMIT_MSG::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: show commit message
        run: |
          echo * Last commit: ${{ env.COMMIT_MSG }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.create_tag.outputs.new_version }}
          release_name: Release ${{ steps.create_tag.outputs.new_version }}
          body: |
            Release notes:
            - ${{ env.COMMIT_MSG }}
          draft: false
          prerelease: false
